name: Spring Boot in Practice CI
on: [push]
#  push:
#    branches:
#      -main
jobs:
  build:
    name: Build ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [
          ch01/spring-boot-app-demo,
          ch02/bean-validation-custom-annotation/spring-boot-app-start,
          ch02/bean-validation-custom-annotation/spring-boot-app-final,
          ch02/bean-validation/spring-boot-app-start,
          ch02/bean-validation/spring-boot-app-final,
          ch02/command-line-runner/spring-boot-app-start,
          ch02/command-line-runner/spring-boot-app-final,
          ch02/configuration-properties,
          ch02/property-sources,
          ch02/spring-application,
          ch02/spring-boot-default-logging/spring-boot-app-start,
          ch02/spring-boot-default-logging/spring-boot-app-final,
          ch02/spring-boot-logging-with-log4j2/spring-boot-app-start,
          ch02/spring-boot-logging-with-log4j2/spring-boot-app-final,
          ch03/configuring-mongodb-database/course-tracker-start,
          ch03/configuring-mongodb-database/course-tracker-final,
          ch03/configuring-relational-database/course-tracker-start,
          ch03/configuring-relational-database/course-tracker-final,
          ch03/creating-custom-spring-data-repository/course-tracker-start,
          ch03/creating-custom-spring-data-repository/course-tracker-final,
          ch03/custom-query-methods/course-tracker-start,
          ch03/custom-query-methods/course-tracker-final,
          ch03/initialize-relational-database-with-schema/course-tracker-start,
          ch03/initialize-relational-database-with-schema/course-tracker-final,
          ch03/manage-domain-objects-with-jpa/course-tracker-start,
          ch03/manage-domain-objects-with-jpa/course-tracker-final,
          ch03/managing-many-to-many-relationship/course-tracker-start,
          ch03/managing-many-to-many-relationship/course-tracker-final,
          ch03/named-query-method/course-tracker-start, 
          ch03/named-query-method/course-tracker-final,
          ch03/using-criteria-api/course-tracker-start,
          ch03/using-criteria-api/course-tracker-final,
          ch03/using-paging-and-sorting-repository/course-tracker-start,
          ch03/using-paging-and-sorting-repository/course-tracker-final,
          ch03/using-query-annotation/course-tracker-start,
          ch03/using-query-annotation/course-tracker-final,
          ch03/using-query-dsl/course-tracker-start,
          ch03/using-query-dsl/course-tracker-final,
          ch04/custom-endpoint/course-tracker-custom-endpoint-start,
          ch04/custom-endpoint/course-tracker-custom-endpoint-final,
          ch04/custom-failure-analyzer/course-tracker-custom-failure-analyzer-start,
          ch04/custom-failure-analyzer/course-tracker-custom-failure-analyzer-final,
          ch04/custom-healthindicator/custom-healthindicator-start,
          ch04/custom-healthindicator/custom-healthindicator-final,
          ch04/spring-boot-actuator-custom-metrics/spring-boot-actuator-custom-metrics-start,
          ch04/spring-boot-actuator-custom-metrics/spring-boot-actuator-custom-metrics-final,
          ch04/spring-boot-actuator-custom-status-mapper,
          ch04/spring-boot-actuator-info-endpoint,
          ch04/spring-boot-actuator-metrics,
          ch04/spring-boot-actuator/spring-boot-app-demo-start,
          ch04/spring-boot-actuator/spring-boot-app-demo-final,
          ch05/http-basic-authentication/course-tracker-start,
          ch05/http-basic-authentication/course-tracker-final,
          ch05/implementing-custom-loginpage/course-tracker-start,
          ch05/implementing-custom-loginpage/course-tracker-final,
          ch05/Implementing-inmemory-authentication/course-tracker-start,
          ch05/Implementing-inmemory-authentication/course-tracker-final,
          ch05/introducing-spring-security/course-tracker-start,
          ch05/introducing-spring-security/course-tracker-final,
          ch05/jdbc-custom-table-authentication-userdetailsservice/course-tracker-start,
          ch05/jdbc-custom-table-authentication-userdetailsservice/course-tracker-final,
          ch05/jdbc-default-authentication/course-tracker-start,
          ch05/jdbc-default-authentication/course-tracker-final,
          ch05/ldap-authentication/course-tracker-start,
          ch05/ldap-authentication/course-tracker-final,
          ch06/email-verification/course-tracker-start,
          ch06/email-verification/course-tracker-final,
          ch06/google-recaptcha/course-tracker-start,
          ch06/google-recaptcha/course-tracker-final,
          ch06/implementing-https/course-tracker-start,
          ch06/implementing-https/course-tracker-final,
          ch06/implementing-vault/course-tracker-start,
          ch06/implementing-vault/course-tracker-final,
          ch06/login-attempt/course-tracker-start,
          ch06/remember-me/course-tracker-start,
          ch06/remember-me/course-tracker-final,
          ch06/user-registration/course-tracker-start,
          ch06/user-registration/course-tracker-final
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Assemble and test
        run: |
          cd ${{ matrix.project }}
          chmod +x mvnw
          ./mvnw clean install
